[workspace]
members = ["seitai", "restarter"]
default-members = ["seitai"]
resolver = "2"

[workspace.dependencies.anyhow]
version = "1.0.82"

[workspace.dependencies.logging]
path = "crates/logging"

[workspace.dependencies.serenity]
version = "0.12.1"
default-features = false
features = ["cache", "client", "gateway", "model", "native_tls_backend"]

[workspace.dependencies.tokio]
version = "1.37.0"
features = ["macros", "net", "rt-multi-thread", "signal"]

[workspace.dependencies.tracing]
version = "0.1.40"

[workspace.dependencies.uuid]
version = "1.8.0"
features = ["v4", "serde"]
