[workspace]
members = ["seitai", "restarter"]
default-members = ["seitai"]

[workspace.dependencies.anyhow]
version = "1.0.72"

[workspace.dependencies.logging]
path = "crates/logging"

[workspace.dependencies.serenity]
git = "https://github.com/serenity-rs/serenity.git"
branch = "next"
default-features = false
features = ["cache", "client", "gateway", "model", "native_tls_backend"]

[workspace.dependencies.tokio]
version = "1.29.1"
features = ["macros", "net", "rt-multi-thread", "signal"]

[workspace.dependencies.tracing]
version = "0.1.37"

[workspace.dependencies.uuid]
version = "1.4.1"
features = ["v4", "serde"]
