[workspace]
members = ["crates/logging", "crates/voicevox", "restarter", "seitai"]
default-members = ["seitai"]
resolver = "2"

[workspace.dependencies.anyhow]
version = "1.0.86"

[workspace.dependencies.http-body-util]
version = "0.1.2"

[workspace.dependencies.hyper]
version = "1.4.1"
features = ["client", "http1"]

[workspace.dependencies.hyper-util]
version = "0.1.7"
features = ["client", "client-legacy", "http1", "tokio"]

[workspace.dependencies.logging]
path = "crates/logging"

[workspace.dependencies.serde]
version = "1.0.208"
features = ["derive"]

[workspace.dependencies.serde_json]
version = "1.0.125"

[workspace.dependencies.serenity]
version = "0.12.2"
default-features = false
features = ["cache", "client", "gateway", "model", "native_tls_backend"]

[workspace.dependencies.tokio]
version = "1.39.2"
features = ["macros", "net", "rt-multi-thread", "signal"]

[workspace.dependencies.tracing]
version = "0.1.40"

[workspace.dependencies.url]
version = "2.5.2"

[workspace.dependencies.uuid]
version = "1.10.0"
features = ["v4", "serde"]
