services:
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest

  web:
    build:
      context: .
      target: development
    tty: true
    volumes:
      - type: bind
        source: Cargo.lock
        target: /usr/src/myapp/Cargo.lock
      - type: bind
        source: Cargo.toml
        target: /usr/src/myapp/Cargo.toml
      - type: bind
        source: crates
        target: /usr/src/myapp/crates
      - type: bind
        source: seitai
        target: /usr/src/myapp/seitai
      - type: bind
        source: restarter
        target: /usr/src/myapp/restarter
    command: /bin/sh -c 'cargo run -p seitai'
    environment:
      DISCORD_TOKEN:
      VOICEVOX_HOST: voicevox
      PGHOST: database
      PGDATABASE: seitai
      PGUSER: seitai
      PGPASSWORD: seitai
  restarter:
    build:
      context: .
      target: development
    tty: true
    volumes:
      - type: bind
        source: Cargo.lock
        target: /usr/src/myapp/Cargo.lock
      - type: bind
        source: Cargo.toml
        target: /usr/src/myapp/Cargo.toml
      - type: bind
        source: crates
        target: /usr/src/myapp/crates
      - type: bind
        source: seitai
        target: /usr/src/myapp/seitai
      - type: bind
        source: restarter
        target: /usr/src/myapp/restarter
    command: /bin/sh -c 'cargo run -p restarter'
    environment:
      - DISCORD_TOKEN
  database:
    image: postgres:15.4
    environment:
      POSTGRES_DB: seitai
      POSTGRES_USER: seitai
      POSTGRES_PASSWORD: seitai
    ports:
      - '5432:5432'
    volumes:
      - type: bind
        source: ./database
        target: /docker-entrypoint-initdb.d
        read_only: true
      - type: volume
        source: database
        target: /var/lib/postgresql/data

volumes:
  database:
    driver: local
