services:
  voicevox:
    ports:
      - 10101:10101
    image: ghcr.io/aivis-project/aivisspeech-engine:cpu-latest
    volumes:
      - type: volume
        source: aivis-data
        target: /home/user/.local/share/AivisSpeech-Engine-Dev
    post_start:
      - command: chown -R 1000:1000 /home/user/.local/share/AivisSpeech-Engine-Dev
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:10101"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  seitai:
    build:
      context: .
      target: development
    depends_on:
      voicevox:
        condition: service_healthy
    tty: true
    volumes:
      - type: bind
        source: Cargo.lock
        target: /usr/src/myapp/Cargo.lock
      - type: bind
        source: Cargo.toml
        target: /usr/src/myapp/Cargo.toml
      - type: bind
        source: crates
        target: /usr/src/myapp/crates
      - type: bind
        source: seitai
        target: /usr/src/myapp/seitai
      - type: bind
        source: restarter
        target: /usr/src/myapp/restarter
    command: /bin/sh -c 'cargo run -p seitai'
    environment:
      DISCORD_TOKEN:
      VOICEVOX_HOST: voicevox
      KANATRANS_HOST: kanatrans
      KANATRANS_PORT: 8080
      PGHOST: database
      PGDATABASE: seitai
      PGUSER: seitai
      PGPASSWORD: seitai
  restarter:
    build:
      context: .
      target: development
    tty: true
    volumes:
      - type: bind
        source: Cargo.lock
        target: /usr/src/myapp/Cargo.lock
      - type: bind
        source: Cargo.toml
        target: /usr/src/myapp/Cargo.toml
      - type: bind
        source: crates
        target: /usr/src/myapp/crates
      - type: bind
        source: seitai
        target: /usr/src/myapp/seitai
      - type: bind
        source: restarter
        target: /usr/src/myapp/restarter
    command: /bin/sh -c 'cargo run -p restarter'
    environment:
      DISCORD_TOKEN:

  kanatrans:
    image: ghcr.io/hexium310/kanatrans
    environment:
      KANATRANS_PORT: 8080
      RUST_LOG: kanatrans=info
    ports:
      - 8080:8080

  database:
    image: postgres:16
    environment:
      POSTGRES_DB: seitai
      POSTGRES_USER: seitai
      POSTGRES_PASSWORD: seitai
    ports:
      - '5432:5432'
    volumes:
      - type: bind
        source: ./database
        target: /docker-entrypoint-initdb.d
        read_only: true
      - type: volume
        source: database
        target: /var/lib/postgresql/data

volumes:
  aivis-data:
    driver: local
  database:
    driver: local
