[package]
name = "restarter"
version = "0.1.4"
edition = "2021"

[dependencies.anyhow]
workspace = true

[dependencies.futures]
version = "0.3.30"

[dependencies.k8s-openapi]
version = "0.22.0"
features = ["latest"]

[dependencies.kube]
version = "0.94.2"

[dependencies.logging]
workspace = true

[dependencies.tokio]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.serenity]
workspace = true
