---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: restarter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restarter
rules:
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restarter
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: restarter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: restarter
