apiVersion: v1
kind: Service
metadata:
  name: voicevox
spec:
  selector:
    app: voicevox
  ports:
    - port: 50021
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: seitai
spec:
  selector:
    app: seitai
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: kanatrans
spec:
  selector:
    app: kanatrans
  ports:
    - port: 8080
  clusterIP: None
