apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seitai
spec:
  serviceName: seitai
  selector:
    matchLabels:
      app: seitai
  template:
    metadata:
      labels:
        app: seitai
    spec:
      containers:
        - name: seitai
          image: ghcr.io/hexium310/seitai
          imagePullPolicy: Always
          env:
            - name: VOICEVOX_HOST
              value: voicevox
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: seitai-secret
                  key: token
            - name: PGHOST
              value: seitai-database
            - name: PGDATABASE
              value: seitai
            - name: PGUSER
              value: seitai
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: seitai.seitai-database.credentials.postgresql.acid.zalan.do
                  key: password
        - name: restarter
          image: ghcr.io/hexium310/restarter
          imagePullPolicy: Always
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: seitai-secret
                  key: token
      serviceAccountName: restarter
