[package]
name = "seitai"
version = "0.1.20"
edition = "2021"

[dependencies.anyhow]
workspace = true

[dependencies.futures]
version = "0.3.30"

[dependencies.hashbrown]
version = "0.14.5"

[dependencies.indexmap]
version = "2.2.6"
features = ["serde"]

[dependencies.lazy-regex]
version = "3.1.0"
features = ["lite"]

[dependencies.logging]
workspace = true

[dependencies.ordered-float]
version = "4.2.0"

[dependencies.regex-lite]
version = "0.1.5"

[dependencies.sea-query]
version = "0.30.7"
default-features = false
features = ["backend-postgres", "derive", "thread-safe"]

[dependencies.sea-query-binder]
version = "0.5.0"
features = ["sqlx-postgres"]

[dependencies.serenity]
workspace = true
features = ["builder", "collector"]

[dependencies.songbird]
version = "0.4.1"
features = ["builtin-queue"]

[dependencies.sqlx]
version = "0.7.4"
features = ["postgres", "runtime-tokio", "tls-native-tls"]

[dependencies.strum]
features = ["derive"]
version = "0.26.2"

[dependencies.symphonia]
version = "0.5.4"
features = ["wav"]

[dependencies.tokio]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.uuid]
workspace = true

[dependencies.voicevox]
path = "../crates/voicevox"

[dev-dependencies.mockall]
version = "0.12.1"
