[package]
name = "seitai"
version = "0.1.17"
edition = "2021"

[dependencies.anyhow]
workspace = true

[dependencies.async-trait]
version = "0.1.74"

[dependencies.hashbrown]
version = "0.14.2"

[dependencies.indexmap]
version = "2.1.0"
features = ["serde"]

[dependencies.lazy-regex]
version = "3.1.0"
features = ["lite"]

[dependencies.logging]
workspace = true

[dependencies.ordered-float]
version = "4.1.1"

[dependencies.regex-lite]
version = "0.1.5"

[dependencies.sea-query]
version = "0.30.2"
default-features = false
features = ["backend-postgres", "derive", "thread-safe"]

[dependencies.sea-query-binder]
version = "0.5.0"
features = ["sqlx-postgres"]

[dependencies.serenity]
workspace = true
features = ["builder", "collector"]

[dependencies.songbird]
git = "https://github.com/serenity-rs/songbird.git"
branch = "next"
features = ["builtin-queue"]

[dependencies.sqlx]
version = "0.7.3"
features = ["postgres", "runtime-tokio", "tls-native-tls"]

[dependencies.strum]
features = ["derive"]
version = "0.25.0"

[dependencies.symphonia]
version = "0.5.2"
features = ["wav"]

[dependencies.tokio]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.uuid]
workspace = true

[dependencies.voicevox]
path = "../crates/voicevox"

[dev-dependencies.mockall]
version = "0.11.4"
