[package]
name = "voicevox"
version = "0.0.0"
edition = "2021"

[dependencies.anyhow]
workspace = true

[dependencies.hyper]
version = "0.14.28"
features = ["http1", "client", "runtime"]

[dependencies.indexmap]
version = "2.0.0"
features = ["serde"]

[dependencies.serde]
version = "1.0.198"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.109"

[dependencies.tracing]
workspace = true

[dependencies.uuid]
workspace = true

[dependencies.url]
version = "2.5.0"
